# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Destrbute apk for testers"
  lane :distributeToTesters do |options|
    release_notes= "\n\n" + changelog_from_git_commits(
      merge_commit_filtering: "exclude_merges",
      commits_count: 40,
      pretty: "- %s"
    )
 
    firebase_app_distribution(
      app: "1:1002622823432:android:9c853fc732acaed51f35bd",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      testers: "karim@ninjaz.ae, abdelazeem263@gmail.com",
      release_notes: "Ninjaz Task" +  release_notes,
      service_credentials_file: options[:firebaseDistFile]
    )
    
  end
end
